services:
  agenda-app:
    container_name: agenda-app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./agenda-app:/agenda-app
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:17-alpine3.20
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env